import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const pages = {
  '/servicios': ['Servicios', 'Capacidades defensivas para organizaciones que necesitan reducir riesgo digital con alcance, límites y entregables documentados.', ['Evaluación de exposición digital', 'Asesoría en gestión de incidentes', 'Diseño de políticas y controles', 'Capacitación en seguridad y protección digital']],
  '/ai-security': ['AI Security / Defensive AI Lab', 'Investigación y prototipado defensivo para evaluar riesgos de sistemas de IA sin facilitar abuso.', ['Evaluación de amenazas y abuso', 'Pruebas controladas y reproducibles', 'Seguridad de aplicaciones con modelos de IA', 'Documentación responsable de hallazgos']],
  '/research': ['Research', 'Publicaremos metodología, alcance, limitaciones, artefactos reproducibles y estado de revisión de cada trabajo.', ['Notas técnicas', 'Evaluaciones defensivas', 'Taxonomías de riesgo', 'Registro de correcciones']],
  '/open-source': ['Open Source', 'El software liberado por LEVIATÁN incluirá licencia, documentación, modelo de amenazas, historial de cambios y canal de seguridad.', ['Herramientas defensivas', 'Conjuntos de pruebas', 'Plantillas de gobernanza', 'Contribuciones trazables']],
  '/security': ['Security', 'La seguridad se gestiona como proceso verificable: identificación, priorización, remediación, comunicación y aprendizaje.', ['Política de vulnerabilidades', 'Dependencias y control de cambios', 'Respaldo y recuperación', 'Registro de incidentes']],
  '/csirt': ['CSIRT', 'LEVIATÁN está desarrollando capacidades de respuesta a incidentes. Esta página no afirma acreditación, membresía ni estatus oficial de CSIRT.', ['Preparación', 'Triage y coordinación', 'Preservación de evidencia', 'Lecciones aprendidas']],
  '/responsible-disclosure': ['Responsible Disclosure', 'Recibimos reportes de buena fe sobre activos bajo nuestro control y coordinamos su validación y corrección.', ['Incluye activo, impacto y pasos reproducibles', 'No accedas a datos de terceros', 'No interrumpas servicios', 'Espera confirmación antes de divulgar']],
  '/governance': ['Governance', 'Nuestra gobernanza separa afirmaciones, evidencia y aspiraciones. Los compromisos públicos deben tener responsable, fecha y registro.', ['Autoridad y rendición de cuentas', 'Gestión de riesgos', 'Conflictos de interés', 'Revisión periódica']],
  '/transparency': ['Transparency', 'Este registro distinguirá controles implementados, trabajo en curso y objetivos futuros. No presentaremos planes como certificaciones.', ['Cambios relevantes', 'Incidentes materiales', 'Solicitudes institucionales', 'Métricas con contexto']],
  '/collaboration': ['Institutional Collaboration', 'Colaboramos mediante objetivos definidos, autorización verificable, minimización de datos y reglas claras de publicación.', ['Instituciones públicas', 'Universidades', 'CERT y CSIRT', 'Laboratorios y empresas de tecnología']],
  '/privacy': ['Privacidad', 'Tratamos únicamente los datos necesarios para responder comunicaciones, prestar servicios autorizados y cumplir obligaciones aplicables.', ['Finalidad y minimización', 'Retención limitada', 'Seguridad razonable', 'Derechos y contacto']],
  '/terms': ['Términos', 'La información pública del sitio es general y no crea por sí misma relación abogado-cliente, garantía ni autorización para realizar pruebas.', ['Uso lícito', 'Propiedad intelectual', 'Limitación de responsabilidad', 'Cambios documentados']],
  '/contacto': ['Contacto', 'Para consultas institucionales, propuestas de colaboración o asuntos de seguridad, utiliza un canal corporativo y evita enviar secretos en el primer contacto.', ['Contacto general: contacto@centrojuridicoleviatan.com', 'Seguridad: security@centrojuridicoleviatan.com', 'Reportes: consulta Responsible Disclosure', 'México · colaboración internacional remota']]
};

const nav = [['Servicios','/servicios'],['AI Security','/ai-security'],['Research','/research'],['Open Source','/open-source'],['Security','/security'],['Governance','/governance']];

function Layout({children}) {
  return <><header><a className="brand" href="/"><span className="mark">L</span><span>Centro Jurídico <b>LEVIATÁN</b></span></a><nav>{nav.map(([n,u])=><a key={u} href={u}>{n}</a>)}</nav><a className="contact" href="/contacto">Contacto</a></header>{children}<footer><div><a className="brand" href="/"><span className="mark">L</span><span>LEVIATÁN</span></a><p>Ciberseguridad, protección digital e investigación defensiva de IA.</p></div><div className="footer-links"><a href="/csirt">CSIRT</a><a href="/responsible-disclosure">Responsible Disclosure</a><a href="/transparency">Transparency</a><a href="/collaboration">Institutional Collaboration</a><a href="/privacy">Privacidad</a><a href="/terms">Términos</a></div><small>© {new Date().getFullYear()} Centro Jurídico LEVIATÁN. Las capacidades y reconocimientos se describen únicamente cuando existe evidencia verificable.</small></footer></>;
}

function Home(){return <Layout><main><section className="hero"><p className="eyebrow">SEGURIDAD CON EVIDENCIA</p><h1>Defensa digital para un entorno de <em>riesgo real.</em></h1><p className="lead">Construimos capacidades verificables en ciberseguridad, protección digital e investigación defensiva de inteligencia artificial.</p><div className="actions"><a className="primary" href="/ai-security">Conocer el laboratorio →</a><a className="secondary" href="/collaboration">Colaboración institucional</a></div><div className="signals"><span>01 · Alcance autorizado</span><span>02 · Evidencia trazable</span><span>03 · Divulgación responsable</span></div></section><section className="statement"><p className="eyebrow">PROPÓSITO</p><h2>La confianza institucional no se declara. <em>Se demuestra.</em></h2><p>Documentamos procesos, controles, investigación, correcciones y límites. Diferenciamos con claridad el estado actual de los objetivos futuros.</p></section><section className="cards"><article><span>01</span><h3>Defensive AI Lab</h3><p>Evaluación responsable de amenazas y controles para sistemas de IA.</p><a href="/ai-security">Explorar →</a></article><article><span>02</span><h3>Security & CSIRT</h3><p>Preparación y respuesta a incidentes con procesos documentados.</p><a href="/csirt">Ver capacidades →</a></article><article><span>03</span><h3>Research & Open Source</h3><p>Publicaciones y herramientas defensivas reproducibles.</p><a href="/research">Consultar investigación →</a></article></section><section className="status"><div><p className="eyebrow">ESTADO INSTITUCIONAL</p><h2>Transparencia desde el principio.</h2></div><p>Estamos formalizando controles y capacidades. No afirmamos certificaciones ISO, membresía FIRST, respaldo gubernamental ni alianzas que no hayan sido obtenidas y publicadas con evidencia.</p><a href="/transparency">Ver transparencia →</a></section></main></Layout>}

function Page({data}){return <Layout><main className="page"><p className="eyebrow">CENTRO JURÍDICO LEVIATÁN</p><h1>{data[0]}</h1><p className="lead">{data[1]}</p><section className="page-grid">{data[2].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Esta capacidad se implementa con alcance autorizado, evidencia conservada y revisión proporcional al riesgo.</p></article>)}</section><aside><strong>Estado y límites</strong><p>La información de esta página describe capacidades y compromisos de trabajo. No implica certificación, afiliación o respaldo de terceros.</p></aside></main></Layout>}

const path = window.location.pathname.replace(/\/$/,'') || '/';
createRoot(document.getElementById('root')).render(path==='/'?<Home/>:pages[path]?<Page data={pages[path]}/>:<Layout><main className="page"><h1>Página no encontrada</h1><a className="primary" href="/">Volver al inicio</a></main></Layout>);
